spring:
  application:
    name: SPRING-CLOUD-ADMIN
  zipkin:
    base-url: http://spring-cloud-zipkin:8084

server:
  port: 8087

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-eureka:8081/eureka/