spring:
  application:
    name: SPRING-CLOUD-ZIPKIN
  boot:
    admin:
      client:
        # spring-clouda-dmin 监控地址
        url: http://spring-cloud-admin:8087
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-eureka:8081/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
